<?php
/**
 * elastic_ChangeLogDataClass
 * @author Ben Kucenski <bkucenski@gmail.com>
 * generated by QuickDRY
 *
 */
 
class elastic_ChangeLogDataClass extends elastic_ChangeLogDataSchema
{
    public function __get($name)
    {
        switch ($name) {
        }

        return parent::__get($name);
    }
    
    public function __set($name, $value)
    {
        switch ($name) {
        }

        return parent::__get($name);
    }

    public function Save() 
    {
        return parent::Save();
    }
}
