<?php
class UserClass extends SafeClass
{
    public $id;
    public $Username;

    public function __get($name)
    {
        switch($name) {
            case 'login':
                return $this->Username;
        }
        return parent::__get($name); // TODO: Change the autogenerated stub
    }

    public static function LogIn($username, $password)
    {
        // bkucenski@instituteforsupplymanagement.org
        $ldap = new adLDAP();
        if($ldap->authenticate($username, $password)) {

            $user = new self();
            $user->Username = $username;
            $user->id = md5($username);
            return $user;

        }
        return null;
    }

    public function Is($roles)
    {
        return true;
    }
}