<?php

use QuickDRY\Connectors\Elastic_A;

/**
 * elastic_ChangeLogDataSchema
 * @author Ben Kucenski <bkucenski@gmail.com>
 * generated by QuickDRY
 */
 
class elastic_ChangeLogDataSchema extends Elastic_A
{
    public static ?string $_index = 'change_log';
    public static ?string $_type = 'data';
    
    public ?string $changes = null;
    public ?string $created_at = null;
    public ?string $database = null;
    public ?string $host = null;
    public ?string $is_deleted = null;
    public ?string $object_type = null;
    public ?string $table = null;
    public ?string $user_id = null;
    public ?string $uuid = null;

}
