<?php
/**
 * elastic_ChangeLogDataSchema
 * @author Ben Kucenski <bkucenski@gmail.com>
 * generated by QuickDRY
 *
 * @property keyword changes
 * @property date created_at
 * @property keyword database
 * @property keyword host
 * @property keyword is_deleted
 * @property keyword object_type
 * @property keyword table
 * @property keyword user_id
 * @property keyword uuid
 */
 
class elastic_ChangeLogDataSchema extends Elastic_A
{
    public static $_index = 'change_log';
    public static $_type = 'data';
    
    public $changes;
    public $created_at;
    public $database;
    public $host;
    public $is_deleted;
    public $object_type;
    public $table;
    public $user_id;
    public $uuid;

    public function __get($name)
    {
        switch ($name) {
        
        }

        return parent::__get($name);
    }
    
    public function __set($name, $value)
    {
        switch ($name) {
        
        }

        return parent::__set($name, $value);
    }
    
    
}
